### ISSUE TITLE
Planner does not handle floating points correctly 

### ISSUE THREAD

**Issue by asaba96** [Pitt-RAS/racecar#22]
The motion planner does not handle floating points correctly, which leads to it being unable to lookup nodes in the occupancy grid and thinking they are not free. Without the rounding, however, the planner never reaches the goal node. 

The longterm solution is to convert everything into an integer representation when planning and convert it back when a plan is found. 

https://github.com/Pitt-RAS/racecar/blob/695c273f0386a92a1e8c192e5c318aa3b82b22b5/src/magellan_motion/src/path_planner/planner.cpp#L89

**Comment by nls5260** [comment]
Would this be along the lines of setting up a map->grid and grid-> map transform where the planner plans according to int grid points (by rounding to nearest one) and convert back to our map coordinates after a path is computed?

**Comment by asaba96** [comment]
@nls5260 no this just means that for each successor, instead of adding and comparing floating points, you use an integer representation. So like 10 for the x pose would actually be 10 times some delta pose in floating-point numbers. 

https://github.com/Pitt-RAS/racecar/blob/master/src/magellan_motion/include/planner.h#L32

**Comment by nls5260** [comment]
So multiplying the float value by 10^n in order to get an integer representation. Then when converting it back dividing by 10^n to get back to the float representation?

**Comment by asaba96** [comment]
No its like your delta pose is .01m and your final node is at <200, 300>, that actually means you're at <2, 3>

**Comment by nls5260** [comment]
Addressed with #31

**Comment by asaba96** [comment]
fixed in #31
