### ISSUE TITLE
Fake Obstacles starts at (0,0)

### ISSUE THREAD

**Issue by asaba96** [Pitt-RAS/racecar#30]
the fake obstacles test script starts generating cells in the grid such that every element is a positive element. It needs to be changed so that the robot is centered at 0,0 and there is an equal amount of known grid around it

https://github.com/Pitt-RAS/racecar/blob/9318e046a2fd3939d9eda3aaaac044fd9ac68666/src/magellan_motion/scripts/fake_obstacles.py#L30

**Comment by nls5260** [comment]
Addressed with #31

**Comment by asaba96** [comment]
fixed in #31
